package http

const (
	TCP_MAX_SEND_QUEUE            = 128 //100万缓冲区
	TCP_DEFAULT_CLIENT_SIZE       = 64
	TCP_DEFAULT_READ_BUFFER_SIZE  = 1024
	TCP_RECV_DEFAULT_SIZE         = 4096
	TCP_DEFAULT_WRITE_BUFFER_SIZE = 4096
	HTTP_POST_TIMEOUT             = 3   //3秒超时
	DEFAULT_LOGIN_TIMEOUT         = 600 //600秒不活动，登录超时
)
