# log level[debug|info|warn|error],default error
log_level : debug

databases : 
-
  host             : 127.0.0.1
  port             : 3306
  user             : replicate
  password         : 123456
  charset          : utf8mb4
  server_id        : 9999
  flavor           : mariadb
  
  heartbeat_period : 30000000000        ## 单位为纳秒，这里的时间是30秒
  read_timeout     : 0                  ## 单位为纳秒
  bin_file         : mysql-bin.000001   ## 
  bin_pos          : 4                  ## 

http : 
  enable    : true               ## 是否启用http服务
  time_tick : 1                  ## 故障检测的时间间隔，单位为秒
  groups    :                    ## 配置文件里面的groups不可以改变
  -
    name   : group1
    filter : []          ## 只订阅这里添加的表，空[]表示全部，如 ["wordpress.wp_comments","seals.*"]
                         ## 为数组，结构为 ["库.表"]，支持正则
    nodes  :             ## 所有的广播节点
    -
      url : http://127.0.0.1:8080/index.php
    -
      url : http://127.0.0.1:8080/index.php
  -
    name   : group2
    filter : []
    nodes  :
    -
      url : http://127.0.0.1:8080/index.php

tcp : 
  enable : true ##启用tcp服务
  listen : 0.0.0.0
  port   : 9990
  groups :
  -
    name   : group1
    filter : []
  -
    name   : group2
    filter : []

cluster : 
  enable     : false
  listen     : 0.0.0.0
  port       : 9999
  service_ip : 192.168.0.105
