addr             = "127.0.0.1:3306"
user             = "replicate"
password         = "123456"
charset          = "utf8mb4"
server_id        = 9999
flavor           = "mariadb"

heartbeat_period = 30000000000 ##单位为纳秒，这里的时间是30秒
read_timeout     = 0 ##单位为纳秒
bin_file         = "mysql-bin.000001"
bin_pos          = 4

