##全局配置
# 0 =	PanicLevel Level = iota
# 1 =	FatalLevel
# 2 =	ErrorLevel
# 3 =	WarnLevel
# 4 =	InfoLevel
# 5 =	DebugLevel
##日志级别，默认为5，即显示所有的日志信息
log_level = 5
time_zone = "Local"

control_listen = "127.0.0.1:6061"
agent_listen = "127.0.0.1:6062"
pprof_listen = "0.0.0.0:5050"
